//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Gen.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP_Gen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 --
        ///-- Dropping stored procedure {0:G} : 
        ///--
        ///
        ///IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[{0:G}]&apos;) AND OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1)
        ///  DROP PROCEDURE [dbo].[{0:G}]
        ///  
        ///GO 的本地化字符串。
        /// </summary>
        internal static string DropProcedure {
            get {
                return ResourceManager.GetString("DropProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {6:G}public {0:G}DataSet {1:G}({2:G})
        ///        {{
        ///            DbObject dbo = new DbObject();
        ///            SqlParameter[] parameters = new SqlParameter[]
        ///                {{
        ///{3:G} 
        ///                }};
        ///            return dbo.RunProcedure(&quot;{4:G}&quot;, parameters, &quot;{5:G}&quot;);
        ///        }} 的本地化字符串。
        /// </summary>
        internal static string ReturnDatasetMethodTemplate {
            get {
                return ResourceManager.GetString("ReturnDatasetMethodTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {5:G}public {0:G}int {1:G}({2:G})
        ///		{{
        ///			int RowsAffected = 0;
        ///			int Result = 0;
        ///			DbObject dbo = new DbObject();
        ///			SqlParameter[] parameters = new SqlParameter[]
        ///				{{
        ///{3:G} 
        ///				}};
        ///			Result = dbo.RunProcedure(&quot;{4:G}&quot;, parameters, out RowsAffected);
        ///			return RowsAffected;
        ///        }} 的本地化字符串。
        /// </summary>
        internal static string ReturnRowsAffectedMethodTemplate {
            get {
                return ResourceManager.GetString("ReturnRowsAffectedMethodTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {5:G}public {0:G}int {1:G}({2:G})
        ///		{{
        ///			int RowsAffected = 0;
        ///			int Result = 0;
        ///			DbObject dbo = new DbObject();
        ///			SqlParameter[] parameters = new SqlParameter[]
        ///				{{
        ///{3:G} 
        ///				}};
        ///			Result = dbo.RunProcedure(&quot;{4:G}&quot;, parameters, out RowsAffected);
        ///			return Result;
        ///        }} 的本地化字符串。
        /// </summary>
        internal static string ReturnScalarMethodTemplate {
            get {
                return ResourceManager.GetString("ReturnScalarMethodTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 new SqlParameter(&quot;{0:G}&quot;,{1:G}) 的本地化字符串。
        /// </summary>
        internal static string SqlParameterTemplate {
            get {
                return ResourceManager.GetString("SqlParameterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT dbid AS ID, NULL AS ParentID, name AS Text FROM [master].[dbo].[sysdatabases] ORDER BY [name] 的本地化字符串。
        /// </summary>
        internal static string strDatabasesList2000 {
            get {
                return ResourceManager.GetString("strDatabasesList2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT database_id AS ID, NULL AS ParentID, name AS Text FROM sys.databases ORDER BY [name] 的本地化字符串。
        /// </summary>
        internal static string strDatabasesList2005 {
            get {
                return ResourceManager.GetString("strDatabasesList2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE {0:G};
        ///
        ///SELECT  Cols.TABLE_NAME,
        ///        Cols.COLUMN_NAME,
        ///        Cols.ORDINAL_POSITION,
        ///        Cols.DATA_TYPE,
        ///		Cols.NUMERIC_PRECISION,
        ///		Cols.NUMERIC_SCALE,		
        ///        Cols.IS_NULLABLE,
        ///        Cols.CHARACTER_MAXIMUM_LENGTH,       
        ///        COLUMNPROPERTY(object_id(Cols.TABLE_NAME), Cols.COLUMN_NAME, &apos;IsIdentity&apos;) AS IsIdentity,
        ///        ( SELECT    COUNT(KCU.COLUMN_NAME)
        ///          FROM      INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU
        ///                    INNER JOIN INFORMATION_SCHEMA.TABLE_CO [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string strTablesAndColumns {
            get {
                return ResourceManager.GetString("strTablesAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT TABLE_NAME FROM [{0:G}].INFORMATION_SCHEMA.TABLES
        ///WHERE TABLE_TYPE = &apos;BASE TABLE&apos;  
        ///AND TABLE_NAME &lt;&gt; &apos;dtproperties&apos;  
        ///ORDER BY TABLE_NAME 的本地化字符串。
        /// </summary>
        internal static string strTablesList {
            get {
                return ResourceManager.GetString("strTablesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon table_sql_create {
            get {
                object obj = ResourceManager.GetObject("table_sql_create", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using System.ComponentModel;
        ///using NovinMedia.Data;
        ///
        ///namespace {0:G}
        ///{{
        ///    [DataObject(true)]
        ///    public class {1:G}
        ///    {{
        ///{2:G}
        ///    }}
        ///}} 的本地化字符串。
        /// </summary>
        internal static string WrapperClass_CSharp_Template {
            get {
                return ResourceManager.GetString("WrapperClass_CSharp_Template", resourceCulture);
            }
        }
    }
}
